version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=storage
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
      - MYSQL_DB=zipkin
      - JAVA_OPTS=-Xms64m -Xmx256m  # Minimize Java heap size
    depends_on:
      storage:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
  
  storage:
    image: openzipkin/zipkin-mysql
    container_name: storage
    ports:
      - "3306:3306"
    command: >
      --max_connections=100
      --innodb_buffer_pool_size=64M
      --key_buffer_size=16M
      --table_open_cache=64
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
